dtdoc edit for "darkroom: Add synchronization of last edited iop to selection."
darktable-org/dtdocs pull request #712
Opened 2024-12-30 20:11 UTC by tnbde

# Please include a link to the Pull Request that you are documenting
[darktable PR#17589](https://github.com/darktable-org/darktable/pull/17589) 
# Tell us a little bit about this pull request 
- The first commit adds in the filmstrip.md an additional item in the shortcut list describing the new shortcut Ctrl+X implemented by the darktable PR metioned above. In addition, I decided to clarify the first sentence, since from my understanding the filmstrip is only available in the darkroom view.
- The second commit is an edit of the last paragraph mentioning the filmstrip module in the darkroom-view-layout.md, so that it is formatted more consistently like all other modules mentioned in this document.

2025-01-01 21:33 UTC, elstoc requested changes

2025-01-01 21:33 UTC, elstoc commented on content/darkroom/darkroom-view-layout.md
> +: You can also enable the filmstrip at the bottom of the screen allowing you to select and interact with the currently selected collection similar to the [lighttable](../lighttable/_index.md) view.
This isn't a formatting error, it's on purpose. The definition list describes the buttons, but filmstrip is not a button. I don't think we should change this.

2025-01-01 21:33 UTC, elstoc commented on content/module-reference/utility-modules/shared/filmstrip.md
> +The filmstrip can be used to quickly switch between images in the darkroom. The images shown are the same as those displayed in the lighttable view and are defined by the currently-selected collectio
This is documented here (under `utility-modules/shared`) because the filmstrip is used in multiple views, not just the darkroom.

2025-01-03 10:21 UTC, tnbde commented on content/module-reference/utility-modules/shared/filmstrip.md
> +The filmstrip can be used to quickly switch between images in the darkroom. The images shown are the same as those displayed in the lighttable view and are defined by the currently-selected collectio
Thanks for the clarification, I only knew the filmstrip module from the darktable view, I will correct it.

2025-01-03 17:13 UTC, tnbde commented on content/darkroom/darkroom-view-layout.md
> +: You can also enable the filmstrip at the bottom of the screen allowing you to select and interact with the currently selected collection similar to the [lighttable](../lighttable/_index.md) view.
One advantage is here, that the filmstrip module is formatted in the same way in this chapter/section, like all other modules as in the left and right panel subsections.

But if it was intended this way, i will correct it. Thanks for the feedback!

2025-01-03 17:22 UTC, elstoc commented on content/darkroom/darkroom-view-layout.md
> +: You can also enable the filmstrip at the bottom of the screen allowing you to select and interact with the currently selected collection similar to the [lighttable](../lighttable/_index.md) view.
I do think there's a good argument for filmstrip being a toggle button on the button bar, but that's another discussion

2025-01-03 17:28 UTC, tnbde commented on content/darkroom/darkroom-view-layout.md
> +: You can also enable the filmstrip at the bottom of the screen allowing you to select and interact with the currently selected collection similar to the [lighttable](../lighttable/_index.md) view.
I agree. This should be reverted now.

2025-01-03 18:50 UTC, elstoc commented
Thanks

2025-01-03 18:51 UTC, merged